# 线上配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bj-cdb-5vbytoyy.sql.tencentcdb.com:28921/boapi?serveTimezone=GMT%2B8
    username: root
    password: Twb12345.
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 47.108.224.156
    port: 6379
    timeout: 5000
    password: twb123
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
